# Generated by Django 6.0 on 2026-01-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('sender', models.TextField(blank=True, null=True)),
                ('filename', models.TextField(blank=True, null=True)),
                ('amount_value', models.FloatField(blank=True, null=True)),
                ('amount_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('due_date_iso', models.DateField(blank=True, null=True)),
                ('saved_path', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
