# Generated by Django 6.0 on 2026-01-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('message_id', models.CharField(db_index=True, max_length=128)),
                ('attachment_id', models.CharField(max_length=256)),
                ('thread_id', models.CharField(blank=True, max_length=128, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('sender', models.TextField(blank=True, null=True)),
                ('msg_date', models.TextField(blank=True, null=True)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('filename', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=200, null=True)),
                ('saved_path', models.TextField(blank=True, null=True)),
                ('extracted_text_len', models.IntegerField(default=0)),
                ('amount_value', models.FloatField(blank=True, null=True)),
                ('amount_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('amount_source', models.CharField(blank=True, max_length=50, null=True)),
                ('due_date_iso', models.DateField(blank=True, db_index=True, null=True)),
                ('due_date_source', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
