# Generated by Django 6.0.1 on 2026-01-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0002_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=128, unique=True)),
                ('attachment_id', models.CharField(blank=True, max_length=256, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('sender', models.TextField(blank=True, null=True)),
                ('msg_date', models.DateTimeField(blank=True, null=True)),
                ('filename', models.TextField(blank=True, null=True)),
                ('saved_path', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
                ('amount_value', models.FloatField(blank=True, null=True)),
                ('amount_currency', models.CharField(blank=True, max_length=8, null=True)),
                ('due_date_iso', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
