# Generated by Django 6.0.1 on 2026-04-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0004_gmailaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailaccount',
            name='last_sync_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gmailaccount',
            name='last_sync_window',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='gmailaccount',
            name='synced_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmailaccount',
            name='synced_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
