# Generated by Django 6.0.1 on 2026-05-10 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0005_gmailaccount_last_sync_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('billdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Bills.billdocument')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
            },
            bases=('Bills.billdocument',),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('billdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Bills.billdocument')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
            },
            bases=('Bills.billdocument',),
        ),
        migrations.RemoveField(
            model_name='billdocument',
            name='due_date_iso',
        ),
        migrations.AddField(
            model_name='billdocument',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billdocument',
            name='document_type',
            field=models.CharField(choices=[('bill', 'Bill'), ('receipt', 'Receipt'), ('general', 'General')], default='general', max_length=16),
        ),
        migrations.AddField(
            model_name='billdocument',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billdocument',
            name='gmail_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_documents', to='Bills.gmailaccount'),
        ),
        migrations.AddField(
            model_name='billdocument',
            name='paid_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billdocument',
            name='payment_method',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='billdocument',
            name='vendor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billdocument',
            name='message_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name='billdocument',
            constraint=models.UniqueConstraint(fields=('gmail_account', 'message_id', 'attachment_id'), name='unique_document_per_gmail_account'),
        ),
    ]
