# Generated by Django 6.0.1 on 2026-05-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0006_bill_receipt_remove_billdocument_due_date_iso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billdocument',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='billdocument',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='billdocument',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='bill',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='paid_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='billdocument',
            name='document_type',
            field=models.CharField(choices=[('bill', 'Bill'), ('receipt', 'Receipt')], max_length=16),
        ),
    ]
